JVC=javac
SERVER=Servidor2
CLIENT1=Cliente
CLIENT2=Cliente2
CA=A
all: ${SERVER}.class ${CLIENT1}.class ${CLIENT2}.class ${CA}.class

${SERVER}.class:	${SERVER}.java
	javac ${SERVER}.java

${CLIENT1}.class: ${CLIENT1}.java
	javac ${CLIENT1}.java

${CLIENT2}.class: ${CLIENT2}.java
	javac ${CLIENT2}.java

${CA}.class: ${CA}.java
	javac ${CA}.java
